# Generated by Django 3.2 on 2021-12-16 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211208_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(related_name='_users_customuser_friends_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='outbound_friend_requests',
            field=models.ManyToManyField(related_name='_users_customuser_outbound_friend_requests_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
