# Generated by Django 4.0 on 2021-12-22 00:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='outbound_friend_requests',
            field=models.ManyToManyField(blank=True, related_name='inbound_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
