# Generated by Django 3.2.9 on 2021-12-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_num', models.IntegerField()),
                ('month_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeaCreature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('shadow_size', models.CharField(max_length=20)),
                ('speed', models.CharField(max_length=20)),
                ('icon', models.URLField()),
                ('month_array', models.ManyToManyField(related_name='sea_creatures', to='critters.Month')),
                ('time_array', models.ManyToManyField(related_name='sea_creatures', to='critters.Time')),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('rarity', models.CharField(max_length=20)),
                ('shadow_size', models.CharField(max_length=20)),
                ('icon', models.URLField()),
                ('month_array', models.ManyToManyField(related_name='fish', to='critters.Month')),
                ('time_array', models.ManyToManyField(related_name='fish', to='critters.Time')),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('rarity', models.CharField(max_length=20)),
                ('icon', models.URLField()),
                ('month_array', models.ManyToManyField(related_name='bugs', to='critters.Month')),
                ('time_array', models.ManyToManyField(related_name='bugs', to='critters.Time')),
            ],
        ),
    ]
