# Generated by Django 3.2.9 on 2021-12-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='hour_am_pm',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
