# Generated by Django 3.2 on 2021-12-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critters', '0002_time_hour_am_pm'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='is_all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bug',
            name='is_all_year',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fish',
            name='is_all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fish',
            name='is_all_year',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seacreature',
            name='is_all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seacreature',
            name='is_all_year',
            field=models.BooleanField(default=False),
        ),
    ]
