# Generated by Django 3.2 on 2021-12-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critters', '0003_auto_20211213_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='month_end',
            field=models.ManyToManyField(related_name='bugs_end', to='critters.Month'),
        ),
        migrations.AddField(
            model_name='bug',
            name='month_start',
            field=models.ManyToManyField(related_name='bugs_start', to='critters.Month'),
        ),
        migrations.AddField(
            model_name='fish',
            name='month_end',
            field=models.ManyToManyField(related_name='fish_end', to='critters.Month'),
        ),
        migrations.AddField(
            model_name='fish',
            name='month_start',
            field=models.ManyToManyField(related_name='fish_start', to='critters.Month'),
        ),
        migrations.AddField(
            model_name='seacreature',
            name='month_end',
            field=models.ManyToManyField(related_name='sea_creatures_end', to='critters.Month'),
        ),
        migrations.AddField(
            model_name='seacreature',
            name='month_start',
            field=models.ManyToManyField(related_name='sea_creatures_start', to='critters.Month'),
        ),
    ]
