# Generated by Django 3.2 on 2021-12-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critters', '0004_auto_20211214_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='month_end',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='month_start',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='month_end',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='month_start',
        ),
        migrations.RemoveField(
            model_name='seacreature',
            name='month_end',
        ),
        migrations.RemoveField(
            model_name='seacreature',
            name='month_start',
        ),
        migrations.AddField(
            model_name='bug',
            name='month_span',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fish',
            name='month_span',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seacreature',
            name='month_span',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
